### ISSUE TITLE
Add seed parameter to gen context block

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#108]
Suggested fix - 

add seed parameter to gen context block in the default flows.

--

**Seed**: This parameter is used to set a seed value for the random number generator used by the model. This allows you to generate reproducible results by providing the same seed value each time.

 If seed is not provided, or the model changes, or the input changes (by as much as a single token) then the result will be a completely new result. It's only there for reproducibility.

**Comment by markmc** [comment]
I don't know what this means? Need a full explanation of what is proposed here

**Comment by aakankshaduggal** [comment]
@markmc -- updated the description, will open a PR with this change.
