### ISSUE TITLE
Drop duplicate columns like `__index_level_0__`

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#109]
We are generating a column `__index_level_0__` in some gen blocks, we need to ensure that we drop them after they are used to avoid redundancy.

**Comment by markmc** [comment]
`full/knowledge.yaml` has:

```
    drop_columns:
      - __index_level_0__
```

at the end. Is it needed elsewhere too?

**Comment by aakankshaduggal** [comment]
@markmc -- Yeah we need it to be changed right after the gen_questions block as well.
