### ISSUE TITLE
Import functions from the ilab repository

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#11]
Some functions that are being called in the `generate_data.py` file are in this file - https://github.com/instructlab/instructlab/blob/main/src/instructlab/utils.py

---

to-do list:

- [x] `DEFAULT_MULTIPROCESSING_START_METHOD`
  - Used in `lab.py` but also this is just a variable
- [x] `DEFAULT_API_KEY`
  - Used in many places but also this is just a variable
- [x] `DEFAULT_MODEL_OLD`
  - Used in `lab.py` but also this is just a variable
- [x] `get_model_family()`
  - Used by `generate_data.py` but also `server.py`
  - https://github.com/instructlab/sdg/pull/46

**From utils, we import the following:**
- [x] `chunk_document()`
  - Only used by `generate_data.py`
  - #35 
- [x] `max_seed_example_tokens()`
  - Only used by `generate_data.py`
  - #35 
- [x] `num_chars_from_tokens()`
  - Only used by `generate_data.py`
  - #35 
- [x] `read_taxonomy()`
  - Used by `generate_data.py` but also `lab.py`
  - https://github.com/instructlab/sdg/pull/46
- [ ] `get_sysprompt()`
  - Used by `generate_data.py` but also `lab.py`, `chat.py` and `make_data.py`
  - https://github.com/instructlab/sdg/pull/89

**Comment by nathan-weinberg** [comment]
@aakankshaduggal @russellb is this something we want to try and preserve commits for? if not I'm happy to take this (and the other issue I guess, seems one PR can resolve both)

**Comment by nathan-weinberg** [comment]
ack @russellb - fine either way - AFAIK the code in question is only used in the CLI currently

**Comment by russellb** [comment]
> ack @russellb - fine either way - AFAIK the code in question is only used in the CLI currently

question is it called from only code other than what got moved here

**Comment by nathan-weinberg** [comment]
Okay looked into this a bit - we import from two locations within `instructlab` - [config](https://github.com/instructlab/instructlab/blob/main/src/instructlab/config.py) and [utils](https://github.com/instructlab/instructlab/blob/main/src/instructlab/utils.py)

**From config, we import the following:**
- `DEFAULT_MULTIPROCESSING_START_METHOD`
  - Used in `lab.py` but also this is just a variable
- `DEFAULT_API_KEY`
  - Used in many places but also this is just a variable
- `DEFAULT_MODEL_OLD`
  - Used in `lab.py` but also this is just a variable
- `get_model_family()`
  - Used by `generate_data.py` but also `server.py`

**From utils, we import the following:**
- `chunk_document()`
  - Only used by `generate_data.py`
- `max_seed_example_tokens()`
  - Only used by `generate_data.py`
- `num_chars_from_tokens()`
  - Only used by `generate_data.py`
- `read_taxonomy()`
  - Used by `generate_data.py` but also `lab.py`
- `get_sysprompt()`
  - Used by `generate_data.py` but also `lab.py`, `chat.py` and `make_data.py`

**Comment by tiran** [comment]
You can write rules for Ruff or PyLint to detect these types of imports and raise an error. InstructLab uses Ruff for that:
```
[tool.ruff.lint.flake8-tidy-imports.banned-api]
"yamllint".msg = "yamllint is for CLI usage only."
```

**Comment by RobotSail** [comment]
This issue is a soft blocker for [#1471](https://github.com/instructlab/instructlab/pull/1471) in the instructlab CLI.

**Comment by RobotSail** [comment]
It looks like `DEFAULT_MULTIPROCESSING_START_METHOD`, `DEFAULT_API_KEY`, and `DEFAULT_MODEL_OLD` are no longer present in SDG, I'll mark those as complete for this epic.

**Comment by russellb** [comment]
The change to remove the last import from the main `instructlab` package is here: https://github.com/instructlab/sdg/pull/89
