### ISSUE TITLE
Add the uuid to each generated sample while saving to messages

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#111]
Add the uuid to each generated sample while saving to messages

``` 
import uuid

def generate_uuid():
     return str(uuid.uuid4())

```

Add this field to the final messages and save this field making with `messages` and `metadata`

final structure to look like  `{'messages' : '', 'metadata': '', 'id' : ''}`

**Comment by markmc** [comment]
Could you add more context, please. What is the use case for a UUID?

**Comment by bbrowning** [comment]
The newer format files output as part of the data mixing work includes a UUID `id` field in every message. I don't know the why behind the `id` field myself, but just noting that we now have one.

**Comment by markmc** [comment]
So we can close this as resolved?
