### ISSUE TITLE
Make use of num_cpus passed in from `ilab` to set num_procs

### ISSUE THREAD

**Issue by russellb** [instructlab/sdg#124]
This came up in PR #120.

We are hard coding num_procs to 8. We expose this as a tunable via the CLI, but are currently not using the value anywhere.

**Comment by markmc** [comment]
Confirmed we're still just using this default:

```
    # The default number of processes to use when performing parallel operations
    # on individual datasets
    DEFAULT_DATASET_NUM_PROCS = 8
```
