### ISSUE TITLE
Add support for batching and parallel data generation

### ISSUE THREAD

**Issue by bbrowning** [instructlab/sdg#167]
The changes from https://github.com/aakankshaduggal/sdg/pull/6 add support for batching and parallel data generation. This issue is to track getting those changes merged into instructlab/sdg main. Part of this work will be to ensure that's the entirety of the necessary batching and data parallel generation commits contained within the referenced pull request and then rebasing/cherry-picking those changes plus any cleanup work required to merge in.

**Comment by bbrowning** [comment]
This may actually be a duplicate of #135 upon further reading, as I see 135 has refocused on getting these types of changes in. Will investigate further and close this one if so.

**Comment by markmc** [comment]
Yep, the description for #135 came from aakankshaduggal/sdg#8 which was superseded by aakankshaduggal/sdg#6

**Comment by bbrowning** [comment]
Ok - closing this as duplicate in favor of continuing to track this in the older #135
