### ISSUE TITLE
Create a utility function to convert from Pandas dataframe to Hugging Face dataset

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#190]
See #142 and https://github.com/instructlab/sdg/pull/163#discussion_r1684206468 and https://github.com/instructlab/sdg/pull/182#discussion_r1688345839

Anywhere we do this conversion, we need to:

```
df = df.reset_index(drop=True)
ds = Dataset.from_pandas(df)
```

to avoid introducing a `__index_level_0__` column

We're starting to build up a number of places where we need to remember to do this, so let's add a utility function

**Comment by hickeyma** [comment]
@markmc I can push a PR for this if thats ok?

**Comment by markmc** [comment]
> @markmc I can push a PR for this if thats ok?

Yep! thanks
