### ISSUE TITLE
data mixing - Fix duplicate context issue by taking set of all context, using sampling without replacement, and comparing text directly instead of row_idx

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#200]
See https://github.com/aakankshaduggal/sdg/pull/18

I understand from @bbrowning that there are bugs to be resolved though:

>  it breaks the pipeline when used with smaller qna.yaml files like the e2e tonsils

**Comment by shivchander** [comment]
See https://github.com/aakankshaduggal/sdg/pull/21 from @abhi1092 for the fixes

**Comment by bbrowning** [comment]
The changes above address multiple areas - the areas specific to generating additional document contexts to add onto the samples to improve training (ie the RAFT changes in the PR above) are opened as a PR at #215.

There are other changes in the fork PR linked above that are unrelated, around things like batch parameters. #215 does not incorporate those.

**Comment by markmc** [comment]
This issue was for "the duplication issue" with  `build_raft_dataset()`, I figured that is resolved by #215 

Do open other issues for anything else
