### ISSUE TITLE
Input dataset for `generate_eval_task_data` should be taxonomy samples, not generated data

### ISSUE THREAD

**Issue by bbrowning** [instructlab/sdg#202]
https://github.com/instructlab/sdg/blob/d5b9c31f4b19ad2029d449dc12507e3c667bf68b/src/instructlab/sdg/generate_data.py#L402

We should be passing the original samples (in `ds`) here to `generate_eval_task_data` instead of the generated samples. See https://github.com/aakankshaduggal/sdg/blob/1dfc0ce2fddfdabade6fd9525c6df33fd455375a/src/instructlab/sdg/generate_data.py#L258 - the original samples from `ds` are the ultimate input to the eval pipeline.

This causes a bug as I try to integrate auxiliary datasets that isn't triggered by the current code, but what happens is we end up getting two different places trying to add a `dataset_type` to the same samples because we're accidentally running the eval pipeline on top of our generated samples instead of on the original samples.

**Comment by markmc** [comment]
See https://github.com/instructlab/sdg/pull/204#discussion_r1690607807
