### ISSUE TITLE
gen_mmlu_knowledge returning empty datasets

### ISSUE THREAD

**Issue by derekhiggins** [instructlab/sdg#213]
From CI but can reproduce locally, more likely with merlinite-7b-lab-Q4_K_M.gguf

While running the mmlu pipeline the model can fail to produce any results with the required start and end tags, in this case the pipeline will end with zero results and 

```
INFO 2024-07-25 11:54:54,080 instructlab.sdg.pipeline:172: Running block: gen_mmlu_knowledge
INFO 2024-07-25 11:54:54,080 instructlab.sdg.pipeline:173: Dataset({
    features: ['icl_document', 'document', 'document_outline', 'domain', 'icl_query_1', 'icl_query_2', 'icl_query_3', 'icl_response_1', 'icl_response_2', 'icl_response_3'],
    num_rows: 10
})
...
  File "/home/runner/work/sdg/sdg/venv/lib/python3.11/site-packages/instructlab/sdg/pipeline.py", line 187, in _generate_single
    raise EmptyDatasetError(
instructlab.sdg.pipeline.EmptyDatasetError: Pipeline stopped: Empty dataset after running block: gen_mmlu_knowledge
```

**Comment by bbrowning** [comment]
I'm starting to see this creep into failures on unrelated PRs now as well, so something we'll need to track down just to keep the CI tests reliably passing.

**Comment by bbrowning** [comment]
From my experience, I would not expect merlinite to be able to reliably follow the instructions at https://github.com/instructlab/sdg/blob/25018dcedd627fdb32dea9e92b8a2473eabf6898/src/instructlab/sdg/configs/knowledge/mcq_generation.yaml . Just like we do for the other pipelines, we're likely going to need a simple and full eval pipeline OR don't run eval at all on the simple pipeline. Both of those I believe require some deeper changes to the eval integration to be able to selectively run simple/full eval or turn it on or off via the pipeline config.
