### ISSUE TITLE
Incorrect Number of Distractor Documents in RAFT-style Prompting Function

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#251]
The `_add_extra_contexts_to_samples` function has a bug in its logic for selecting distractor documents when applying RAFT-style prompting. This bug results in inconsistencies in how context documents are selected and combined, potentially leading to unintended behavior.

**Problems Identified:**

1. **Sampling Error:** The function incorrectly samples five documents instead of the intended four, leading to an incorrect number of documents in the context.

2. **Conditional Addition of the Answer Document:** The function only adds the answer document if the sampling results in fewer than five documents. This is incorrect; the answer document should always be included, regardless of the number of documents sampled.

cc - @abhi1092 @shivchander

**Comment by bbrowning** [comment]
I'm not Aakanksha, but yes #252 closes this issue.

**Comment by hickeyma** [comment]
Closing as fixed by #252
