### ISSUE TITLE
Make it more obvious which names are public

### ISSUE THREAD

**Issue by tiran** [instructlab/sdg#30]
The synthetic data generation code was moved to a separate package `instructlab.sdg` so it can be consumed by multiple projects. The current project layout does not make it obvious which names are designed for public consumption with a stable API, and which are internal implementation details.

I recommend:
- prefix all modules with `_`, e.g. `_generate_data.py` and `_utils.py`
- import public names in `__init__.py` and include them in `__all__` variable.

**Comment by russellb** [comment]
Thanks, @tiran.

I expect this code to receive a significant overhaul in the next week or two. I will be sure to ensure these suggestions are incorporated.

FYI @oindrillac @aakankshaduggal @shivchander

**Comment by markmc** [comment]
I think this is complete as of #73
