### ISSUE TITLE
Repo needs `release-strategy.md` document

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/sdg#330]
Per the [organization governance](https://github.com/instructlab/dev-docs/blob/main/docs/library-release-strategy.md#proposal), this library needs to add a `release-strategy.md` doc to the `docs/` folder - see the linked document for details

**Comment by nathan-weinberg** [comment]
@instructlab/sdg-maintainers please prioritize this to bring your repo into compliance with org policy - I'm seeing gaps emerge due to a lack of defined process here

**Comment by bbrowning** [comment]
This would be helpful for me, as I've never cut a release of SDG and don't know the checklist we typically follow. Do we just push a new tag to GitHub? A release branch? Do we do things like adjust the CI config of the release branch, pinning `ilab` versions in those e2e tests to the appropriate release branch of the CLI repo? Any other references in our tests or code to `main` branch that we have to adjust on the release branch after creating it? That kind of stuff is all unknown to me.

**Comment by nathan-weinberg** [comment]
@bbrowning the linked Dev Doc has some high-level requirements, apart from those it's Maintainer discretion - I would recommend using https://github.com/instructlab/eval/blob/main/docs/release-strategy.md as a starting point (or even just making a carbon copy with updated references and merging that so y'all have something to iterate off of)

**Comment by bbrowning** [comment]
This was fixed by #381
