### ISSUE TITLE
Repo needs `CHANGELOG.md` document

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/sdg#331]
Per the [organization governance](https://github.com/instructlab/dev-docs/blob/main/docs/library-release-strategy.md#proposal), this library needs to add a `CHANGELOG.md` doc to the root folder - see the linked document for details

**Comment by nathan-weinberg** [comment]
@instructlab/sdg-maintainers please prioritize this to bring your repo into compliance with org policy

**Comment by bbrowning** [comment]
We definitely need to do this before release v0.7.x, as that one will have some larger changes from the research sync. I have a concrete need for this as part of the research changes, but holding off creating a CHANGELOG.md in that PR just to not make it any bigger.
