### ISSUE TITLE
Data Mixing Phase 10 - knowledge pre-training dataset not getting mixed in

### ISSUE THREAD

**Issue by khaledsulayman** [instructlab/sdg#365]
The knowledge pre-training dataset isn't getting mixed in for phase 10 usage. The result is that models don't have as good knowledge performance as they should have.

**Comment by ktam3** [comment]
Per @mairin - we also want to backport this in an ilab .19.z release for a downstream z release

FYI @nathan-weinberg @cdoern

**Comment by nathan-weinberg** [comment]
> Per @mairin - we also want to backport this in an ilab .19.z release for a downstream z release
> 
> FYI @nathan-weinberg @cdoern 

I'm not sure this makes any sense? 0.21.0 is almost out...

**Comment by mairin** [comment]
@nathan-weinberg downstream z-release.

**Comment by nathan-weinberg** [comment]
> @nathan-weinberg downstream z-release.

Right, but what I'm saying is from a support cycle standpoint, upgrading to the latest downstream release makes more sense than releasing a Z-stream no?

**Comment by nathan-weinberg** [comment]
@mairin and I sorted it offline 👍
