### ISSUE TITLE
Re-organize API exports

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#63]
Below is a list of out current API exports and a proposal for how they should be exposed

Top-level package:

- `sdg.generate_data()` - This is the main interface used by the CLI. Long-term I question whether this belongs in the library (see #instructlab/instructlab#1519)
- `sdg.SDG` -> I propose removing it in #61
- `sdg.pipeline.Pipeline` -> `sdg.Pipeline` (same for `PipelineContext`)
- `sdg.block.Block` -> `sdg.Block`

Blocks:

- `sdg.filterblock.FilterByValueBlock` -> `sdg.FilterByValueBlock`
- `sdg.importblock.FilterByValueBlock` -> `sdg.ImportBlock`
- `sdg.llmblock.LLMBlock` -> `sdg.LLMBlock`
- `sdg.llmblock.ConditionalLLMBlock` -> `sdg.ConditionalLLMBlock`
- `sdg.utilblocks.SamplePopulatorBlock` -> `sdg.SamplePopulatorBlock`
- `sdg.utilblocks.SelectorBlock` -> `sdg.SelectorBlock`
- `sdg.utilblocks.CombineColumnsBlock` -> `sdg.CombineColumnsBlock`

Default pipelines:

- `sdg.SIMPLE_PIPELINES_PACKAGE` and `sdg.FULL_PIPELINES_PACKAGE`

Exceptions:

- `FilterByValueBlockError`
- `EmptyDatasetError`
- `PipelineConfigParserError`
- `GenerateException`
- `TaxonomyReadingException`

**Comment by russellb** [comment]
related issue: #30
