### ISSUE TITLE
Further update chunking strategies to improve performance.

### ISSUE THREAD

**Issue by PalmPalm7** [instructlab/sdg#66]
This issue is a follow-up on this issue: https://github.com/instructlab/sdg/issues/34, and the PR attempting to resolve it: https://github.com/instructlab/sdg/pull/65.

This issue attempts to improve on the following things.
0. Implement document-specific chunking from the original PR where dependency was in a soft freeze state. 
1. Address the maximum chunk length issue 
2. A benchmark leveraging, DeepEval, Truera, or other methods to evaluate how much the retrieval from RAG could be improved.
3. Improve heuristics logic to take-in numerous file formats and corresponding parsing and chunking.
4. Experiment with semantic chunking, leveraging granite to create chunk embeddings.

cc: @aakankshaduggal @abhi1092 @shivchander

**Comment by ktam3** [comment]
Per our convo, closing this as done
