### ISSUE TITLE
Remove dependencies on instructlab/instructlab

### ISSUE THREAD

**Issue by RobotSail** [instructlab/sdg#88]
This repository currently has dependencies on values from `instructlab.configuration`, which is consuming SDG.

Specifically, the `utils.py` is [importing values from configuration](https://github.com/instructlab/sdg/blob/44ab07de8c44622f37edfcb480d0b38cf0018373/src/instructlab/sdg/utils.py#L16) that will no longer exist 
with this PR in instructlab: [instructlab #1471](https://github.com/instructlab/instructlab/pull/1471).

In general, it's a bad practice for a consuming library to depend on these values as it is a circular dependency.

SDG should either parameterize these values or have its own concept for `DEFAULT_API_KEY` and `DEFAULT_MODEL_OLD`
so as to decouple itself from the instructlab CLI in this direction.

**Comment by RobotSail** [comment]
Closing this as it seems to have already been resolved.

**Comment by russellb** [comment]
Yeah, this was just true during transition because the code that started the repo was extracted from the instructlab repo

**Comment by russellb** [comment]
#11 tracked the steps remaining
