### ISSUE TITLE
[EPIC] Data mixing

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#95]
- [ ] Include data mixing that mixes the newly generated data with the pre-computed dataset. Add this functionality to the utils
- [ ] After the generation is completed, call the data mixing method and create a new dataset that comprises of the pre-computed + new generated data(messages format) and this new data is passed over to training.

**Comment by russellb** [comment]
It would also be great if someone could draft a proposed CLI UX for this functionality. What info is needed from a user? How and where would they provide it?

**Comment by markmc** [comment]
See also aakankshaduggal/sdg#4

**Comment by markmc** [comment]
Replaced by #162
