### ISSUE TITLE
Grounded flow missing num_samples

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/sdg#99]
The `default_flows.py` file is missing the key num_samples for the grounded flow. Adding those can help run e2e for the grounded workflow.

Error :

`ERROR 2024-07-08 15:37:53,495 block.py:37: _validate Missing key: 'num_samples'`

**Comment by markmc** [comment]
I'm pretty confident this has been fixed, e.g. by commit 88f5003

Please re-open if not
